#! /bin/zsh

characters=""

# Ask confirmation to continue release process
read -k "confirmation?Do you want to launch the UnitTests? (Enter y/yes):"
if [[ $confirmation =~ ^(y|yes)$ ]]; then
    echo "Yes!"
fi